/*
	System modules
*/
#include <stdio.h>
#include <stdbool.h> // For booleans in C
#include <stdlib.h>	 // For dynamic memory management i.e. dynamic arrays

/*
	External modules program uses
*/
#include "Definitions.h"
#include "Create_Array.h"
#include "Print.h"
#include "Test_Input.h"


/**
	Returns a restricted integer value which will be the size of 
	the array. Set so that the array cannot be less than 1 in size. We wouldn't
	want a negative array now would we?
 */
int get_array_size()
{
	const char PROMPT[] = "Enter the size of the array: ";
	const int MIN_ARRAY_SIZE = 1;
	int array_size;

	array_size = read_integer_min_restricted(PROMPT, MIN_ARRAY_SIZE);

	return array_size;

}

/**
	
 */
void debug_menu()
{

}

/**
	Central function to debug module
 */
void debug()
{
	const int STARTING_3D_VALUE = 1; 
	const int STARTING_4D_VALUE = 1; 
	// For 3D and 4D arrays, more elements in the nth dimension will be added as solutions are generated

	const int STARTING_NO_OF_SOLUTIONS = 0;

	// Declaring solution storing struct
	chessboard_array n_queens_solutions;

	// Ask user for n amount of queens to solve for
	n_queens_solutions.max = get_array_size();

	// Create array to store solutions (3D array that stores solution, row and column)
	n_queens_solutions.solutions = create_3D_array(n_queens_solutions.max, n_queens_solutions.max, STARTING_3D_VALUE);

	// Set number of solutions currently found to 0
	n_queens_solutions.no_of_solutions = STARTING_NO_OF_SOLUTIONS;

	// Print debug and non debug versions of chessboard
	print_3D_array(n_queens_solutions.solutions, 1, n_queens_solutions.max, true, true);
	print_3D_array(n_queens_solutions.solutions, 1, n_queens_solutions.max, true, false);

	printf("Array for chessboard has been created. \n");

	// Create array that stores all attempts to every solution
	int ****solution_attempts = create_4D_array(n_queens_solutions.max, n_queens_solutions.max, STARTING_3D_VALUE, STARTING_4D_VALUE);
	

	printf("Array for storing all solution attempts has been created. \n");

	// Solve n queens problem


	// Print out solution generated by program, debug and non debug versions for both arrays

}