/*
	System modules
*/
#include <stdio.h>
#include <stdbool.h> // For booleans in C
#include <stdlib.h>	 // For dynamic memory management i.e. dynamic arrays

/*
	External modules program uses
*/
#include "Definitions.h"
#include "Create_Array.h"
#include "Print.h"
#include "Test_Input.h"
#include "Modify_Array.h"


/**
	Returns a restricted integer value which will be the size of 
	the array. Set so that the array cannot be less than 1 in size. We wouldn't
	want a negative array now would we?
 */
int get_array_size()
{
	const char PROMPT[] = "Enter the size of the array: ";
	const int MIN_ARRAY_SIZE = 1;
	int array_size;

	array_size = read_integer_min_restricted(PROMPT, MIN_ARRAY_SIZE);

	return array_size;

}

/**
	
 */
void debug_menu()
{

}

/**
	Central function to debug module
 */
void debug()
{
	const int STARTING_1D_VALUE = 1;
	const int STARTING_3D_VALUE = 1; 
	const int STARTING_4D_VALUE = 1; 
	// For 3D and 4D arrays, more elements in the nth dimension will be added as solutions are generated

	const int STARTING_NO_OF_SOLUTIONS = 0;
	const int TEST_NO_OF_ITERATIONS = STARTING_NO_OF_SOLUTIONS + 1;
	// 0 Can't be inserted into array printing functions since that won't print anything out for us debuggers to see :)

	const bool SOLUTION_ARRAY = true;

	const bool DEBUG = true;
	const bool NO_DEBUG = false;

	chessboard_array n_queens_solutions; // Declaring solution storing struct
	debug_chessboard_array debug; // Stores all attempts at all solutions

	// Ask user for n amount of queens to solve for
	int n_queens = get_array_size();
	n_queens_solutions.max = n_queens;

	// Create array to store solutions (3D array that stores solution, row and column)
	n_queens_solutions.solutions = create_3D_array(n_queens_solutions.max, n_queens_solutions.max, STARTING_3D_VALUE);

	// Set number of solutions currently found to 0
	n_queens_solutions.no_of_solutions = STARTING_NO_OF_SOLUTIONS;

	// Print debug and non debug versions of chessboard
	print_3D_array(n_queens_solutions.solutions, TEST_NO_OF_ITERATIONS, n_queens_solutions.max, SOLUTION_ARRAY, DEBUG);
	print_3D_array(n_queens_solutions.solutions, TEST_NO_OF_ITERATIONS, n_queens_solutions.max, SOLUTION_ARRAY, NO_DEBUG);

	printf("Array for chessboard has been created. \n");

	// Set values to debug custom type
	debug.solution_attempts = create_4D_array(n_queens_solutions.max, n_queens_solutions.max, STARTING_3D_VALUE, STARTING_4D_VALUE);
	debug.no_of_attempts = create_1D_array(STARTING_1D_VALUE);
	debug.no_of_solutions = STARTING_NO_OF_SOLUTIONS;

	// Print debug array
	print_4D_array(debug.solution_attempts, TEST_NO_OF_ITERATIONS, TEST_NO_OF_ITERATIONS, n_queens, DEBUG);
	print_4D_array(debug.solution_attempts, TEST_NO_OF_ITERATIONS, TEST_NO_OF_ITERATIONS, n_queens, NO_DEBUG);

	printf("Array for storing all solution attempts has been created. \n");

	// FOR DEBUGGING PURPOSES ONLY: Testing of array modification functionality
	// Add dimension to the solutions and debug arrays

	const int NEW_ARRAY_SIZE = 2; 
	// Needs to be hard coded since no solutions have been found yet, and I don't want to hardcode that :P
	const bool NOT_CHESSBOARD = false;

	add_to_3D_array(n_queens_solutions.solutions, NEW_ARRAY_SIZE, n_queens);
	printf("Dimension added to n queens array\n");

	add_to_4D_array(debug.solution_attempts, NEW_ARRAY_SIZE, n_queens);
	printf("Dimension added to the debug array\n");

	add_to_1D_array(debug.no_of_attempts, NEW_ARRAY_SIZE);
	printf("Dimensions added to number of attempts array in the debug variable\n");

	printf("Printing out the n_queens, debug and no_of_attempts arrays\n");
	print_3D_array(n_queens_solutions.solutions, NEW_ARRAY_SIZE, n_queens_solutions.max, SOLUTION_ARRAY, DEBUG);
	print_4D_array(debug.solution_attempts, NEW_ARRAY_SIZE, TEST_NO_OF_ITERATIONS, n_queens, DEBUG);
	print_1D_array(debug.no_of_attempts, NEW_ARRAY_SIZE, NOT_CHESSBOARD, NO_DEBUG);

	// Solve n queens problem


	// Print out solution generated by program, debug and non debug versions for both arrays

}